{% set name = "get-docker-secret" %}
{% set version = "1.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 684b35a792db56ceb5d52ee015670ad7710625ab20c9ff855ae88a23ceb5fe3a

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - get_docker_secret

about:
  home: https://github.com/fischerfredl/get-docker-secret
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Utility function to fetch docker secrets/envvars.
  dev_url: https://github.com/fischerfredl/get-docker-secret

extra:
  recipe-maintainers:
    - lincrosenbach
    - nicoddemus
    - nobreconfrade
