{% set name = "get-docker-secret" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3b39eab1caa69b4f7863fd3d9b419e0435c25f4747a1847de5a08161fe8d3410

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=2.7
    - setuptools
  run:
    - python >=2.7

test:
  imports:
    - get_docker_secret

about:
  home: https://github.com/fischerfredl/get-docker-secret
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Utility function to fetch docker secrets/envvars.
  dev_url: https://github.com/fischerfredl/get-docker-secret

extra:
  recipe-maintainers:
    - lincrosenbach
    - nicoddemus
    - nobreconfrade
