travis:
  secure:
    BINSTAR_TOKEN: Ss1eq5tt7k9Bwg+DYwtdKinr9848B5dGfVavMD44YLZAY6elKPJEctpO0Fa5EFjWQdhMmQjafBpgToaaVUm8sr1v4f9frNMfXSvW2yySYr/EHsAYFbEC5eqE+Ot2hKdOeE892spl11o4ujWn5cMNsUSC0rMWG4RVDuC93zL2K2Pyf2I3vKodRqSYucUaMsNg3HLnHgsWBINR5p1OFe9pjHQUmthwkOKSc/q/rryPxOcIIg7pIktHOpTGsLQqzC7Ermbqw+BYoUB48hSGRrFecIZ4YJzVwfTRqkuUKCsOpzsGIG2zm0jaKCr3XK40BoKcjz9ZzBuN2RO5zjLeq8x4dccIKLSfkdUcT4+rmRrJ+jI5bD9By7zWDVXIPJDJUe23+91i2tbC0AtX2EqbbzgebHgr6gebce9wY6d3dg+UiwP9pGpo/nn7g5qMwkHyxYpblgslVUQ3rA3ew6HyJRdzAU1V+9Tjw/a65WAyRM0N9EW8AmEf3RdoBZI6aPgA9NzZnQpO17QOWwd4fF/RTw8JJDGE9jziS//qsWsHV7n35Zli/jDwhsLXIIqfUy9FKZwoCfILj8uESHUY+GKvXCWYOMgXgugm3+8R0OSGEIMBD38AhyyyLyoLGtaLnlC8HeaOmwbMtgrdb3vkdP5at+3IHf2Myo+9vnrUPxVCkpIkQSQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
